Types and variables
endrjuki/c-sharp-syllabus pull request #2
Opened 2021-07-15 09:29 UTC by endrjuki

2021-07-17 09:42 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Solutions/CalculateArea/Geometry.cs
> +{
Types and variables vai arithmetic?

2021-07-19 07:42 UTC, endrjuki commented on csharp-basics/exercises/Arithmetic/Solutions/CalculateArea/Geometry.cs
> +{
Izņēmu `Arithmetic` uzdevumus no šī branch.

2021-07-19 10:24 UTC, endrjuki commented on csharp-basics/exercises/Arithmetic/Solutions/CalculateArea/Geometry.cs
> +{
Tikai tagad atkal jautājums -> vai šo zaru mergojot to main, nepazaudēšu visus Arithmetic uzdevumus?

2021-07-19 19:25 UTC, ausmoons commented on csharp-basics/exercises/Arithmetic/Solutions/CalculateArea/Geometry.cs
> +{
Kāpēc, lai pazaudētu?

2021-07-19 19:26 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Casting/Program.cs
> +            int sum = Convert.ToInt32(a) + b + c + (int)d + (int)e;
Izlabo string ar mazo burtu

2021-07-19 19:35 UTC, ausmoons requested changes

2021-07-19 19:35 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Exercise5/Program.cs
> +            if (times == 0) return "";
return times==0? string.Empty :...

2021-07-19 19:35 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Exercise6/Program.cs
> +            while (true)
Nav labi likt vnk while(true)

2021-07-19 19:35 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Exercise6/Program.cs
> +            while (true)
Kāds tev ir mērķis šim? Validācija?

2021-07-19 19:35 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Exercise6/Program.cs
> +            numberSeries = numberSeries.Replace(" ", "");
Ko maina atstarpju izņemšana?

2021-07-19 19:35 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Exercise8/Program.cs
> +        private const int HoursInDay = 24;
_hoursInDay

2021-07-20 11:04 UTC, endrjuki commented on csharp-basics/exercises/TypesAndVariables/Exercise6/Program.cs
> +            numberSeries = numberSeries.Replace(" ", "");
To, ka programma pieņems gan "1,2,3,4,5", gan "1, 2, 3, 4, 5".

Līdzīga iemesla pēc, kāpēc pie dažādiem promptiem mēs mēdzam downcase lietotāja ievadi (piemēram, kad jāievada "y" / "n", pieņemam arī "Y" un "N")

2021-07-20 11:08 UTC, endrjuki commented on csharp-basics/exercises/TypesAndVariables/Exercise6/Program.cs
> +            while (true)
Validācija, kamēr `!Regex.IsMatch(userInput, "[^0-9, ]")` neizpildīsies, no `while(true)` ārā netikt. Es varētu ieviest varbūt kādu `true/false` mainīgo, varbūt `validInputReceived`, vai kaut ko tamlīdzīgu, un izmantot to cilpā -> piemēram `while (!validInputReceived)`, bet tas jau īsti neko nemaina.

2021-07-20 11:22 UTC, endrjuki commented on csharp-basics/exercises/TypesAndVariables/Exercise8/Program.cs
> +        private const int HoursInDay = 24;
Konfliktējoša informācija tieši ar konstantēm, tieši pirmstam arī meklēju par šo problēmu. Itkā gribējās likt `_`, bet -> https://stackoverflow.com/questions/242534/c-sharp-naming-convention-for-constants 

Uzprasīšu Edgaram un ņemšu viņa vārdus par galavārdu.

2021-07-20 11:32 UTC, endrjuki commented on csharp-basics/exercises/Arithmetic/Solutions/CalculateArea/Geometry.cs
> +{
Nezinu, jo `Arithmetics` zars jau ir iemērdžots `main`ā, un tagad man vēl `TypesAndVariables` zarā bija `Arithmetics` uzdevumi, kurus es izdzēsu. Domāju, vai šī izdzēšanas izmaiņa nestrādās arī uz `main`? Es ar git esmu nočakarējies vairāk, nekā ar programēšanu pagaidām 🤦

2021-07-20 11:32 UTC, endrjuki commented on csharp-basics/exercises/TypesAndVariables/Casting/Program.cs
> +            int sum = Convert.ToInt32(a) + b + c + (int)d + (int)e;
done

2021-07-20 12:11 UTC, endrjuki commented on csharp-basics/exercises/TypesAndVariables/Exercise8/Program.cs
> +        private const int HoursInDay = 24;
Pārmainīju uz `_camelCase` pēc Edgara vārdiem. Man `StyleCop`am gan nepatīk šī izmaiņa, vairs nelietošu šo paplašinājumu.

2021-07-20 12:12 UTC, endrjuki commented on csharp-basics/exercises/TypesAndVariables/Exercise5/Program.cs
> +            if (times == 0) return "";
done

2021-07-20 17:42 UTC, ausmoons approved these changes

2021-08-12 08:16 UTC, closed without merging