Control of flow
endrjuki/c-sharp-syllabus pull request #4
Opened 2021-07-19 10:56 UTC by endrjuki

2021-07-19 19:38 UTC, ausmoons commented on README.md
> +
Kāpēc Readme laboji?

2021-07-19 19:38 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/FlowControl/Exercise5/Program.cs
> +            Console.WriteLine("Please enter a string");
Enter text

2021-07-19 19:40 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/FlowControl/Exercise5/Program.cs
> +                        int keyPressCount = Array.IndexOf(keyArray, character) + 1;
Ko tu te dari un kāpēc?

2021-07-19 19:42 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/FlowControl/TenBillion/Program.cs
> +            if (number >= 10_000_000_000)
Kāpēc apakšsvītras?

2021-07-19 19:44 UTC, ausmoons commented on csharp-basics/exercises/FlowOfControl/FlowControl/TenBillion/Program.cs
> +                   number / (int) Math.Pow(10, targetDigitCount) == 0;
Kāpēc tu šo dari?

2021-07-19 19:44 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Exercise5/Program.cs
> +
Te ir liekas tukšas rindas

2021-07-19 19:45 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Exercise5/Program.cs
> +    class Table {
{ jaunā rindā

2021-07-19 19:46 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Exercise5/Program.cs
> +            int longestIdxLength = _teachers.Length.ToString().Length;
Tev šis jau kaut kur nebija? Es jau redzēju tādu kodu

2021-07-19 19:48 UTC, ausmoons requested changes

2021-07-19 19:48 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Exercise6/Program.cs
> +            return numberSeries.Split(",").Aggregate(0, (accumulator, strNum) =>
Arī šo es jau kaut kur redzēju

2021-07-19 19:48 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Exercise7/Program.cs
> +            Console.WriteLine("Please enter a string");
Enter text, string is type

2021-07-19 19:48 UTC, ausmoons commented on csharp-basics/exercises/TypesAndVariables/Exercise8/Program.cs
> +        private const int DaysInYear = 365;
_daysInYear

2021-07-20 10:02 UTC, endrjuki commented on README.md
> +
Es nezinu kā, bet `README.md` nonāca kaut kādi git meta-dati (head, file hashi utt.). No tiem arī mēģināju tikt vaļā

2021-07-20 10:11 UTC, endrjuki commented on csharp-basics/exercises/FlowOfControl/FlowControl/Exercise5/Program.cs
> +            Console.WriteLine("Please enter a string");
done

2021-07-20 10:31 UTC, endrjuki commented on csharp-basics/exercises/FlowOfControl/FlowControl/Exercise5/Program.cs
> +                        int keyPressCount = Array.IndexOf(keyArray, character) + 1;
Tātad, mēs iterējam caur `input` chariem ar `foreach`.

Ja `character` ir `a`, `b` vai `c`, mēs inicializējam `keyArray` ar visiem šiem burtiem, kas atrodās uz šīs vienas pogas (pogas 2 šajā gadījumā)

Pieņemsim, ka mūsu `character` šoreiz ir `c`. Mēs izmantojam `Array.IndexOf` metodi, lai atrastu šī `char` indeksu, pēctam pieskaitam `1`, jo masīvu indeksi C# sākās ar 0. Tā mēs iegūstam vērtību, ko piešķiram `keyPressCount`.

Šī vērtība apzīmē to, cik reizes mums ir jānospiež šī poga "2", lai iegūtu burtu `c`. Parcik `c` ir pēdējais burts uz šīs pogas, mums būs jānospiež "2" 3 reizes (`Array.IndexOf` atgriezīs 2 un mēs pieskaitam vēl 1).

Pēctam `for` ciklā mēs pievienojam šo "2" pie `numberSequence` `keyPressCount` reizes

2021-07-20 10:33 UTC, endrjuki commented on csharp-basics/exercises/FlowOfControl/FlowControl/TenBillion/Program.cs
> +            if (number >= 10_000_000_000)
Apakšvītras lasāmības dēļ, `10_000_000_000` manā skatījumā ir lasāmāks, nekā `10000000000` https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-7.0/digit-separators

2021-07-20 10:47 UTC, endrjuki commented on csharp-basics/exercises/FlowOfControl/FlowControl/TenBillion/Program.cs
> +                   number / (int) Math.Pow(10, targetDigitCount) == 0;
tātad, pieņemsim, ka mums ir skaitlis `101` un mēs vēlamies noskaidrot ciparu skaitu.

Pirmais jautājums pēc programas būs
Vai šajā skaitlī ir 2 cipari? -> `101 / 10` nav nulle , un `101 / 100` arī nav nulle, līdz ar to `IsDigitCountCorrect` atgriež `false` un mēs virzamies uz nākošo zaru

Vai šajā skaitlī ir 3 cipari -> `101 / 100` nav nulle un `101/1000` ir nulle, līdz ar to `IsDigitCountCorrect` atgriež `true` un mēs mainīgajam `digits` piesķiram vērtību `3`.

Šī metode ir šīs loģikas vispārinājums, lai man būtu tikai jāiekopē metodes nosaukums un jānomaina `targetDigitCount` šajos if zaros.

Vispār jau es gribētu ciparu skaitu iegūt vienkārši pārvēršot par stringu un izmantojot `Length` property, bet par cik pakas nosaukums ir `Flow Control` un tie daudzie ifi jau bija doti, izvēlējos šādu risinājumu

2021-07-20 10:51 UTC, endrjuki commented on csharp-basics/exercises/TypesAndVariables/Exercise5/Program.cs
> +            int longestIdxLength = _teachers.Length.ToString().Length;
Man ir pull requests ar `TypesAndVariables` uzdevumiem no pagājušās nedēļas. Izskatās, ka man atkal ir izdevies kaut kā samīcīt tos `TypesAndVariables` kopā ar `FlowControl`

2021-07-20 12:07 UTC, endrjuki commented on csharp-basics/exercises/TypesAndVariables/Exercise5/Program.cs
> +
done

2021-07-20 12:08 UTC, endrjuki commented on csharp-basics/exercises/TypesAndVariables/Exercise5/Program.cs
> +    class Table {
done

2021-07-20 12:20 UTC, endrjuki commented on csharp-basics/exercises/TypesAndVariables/Exercise7/Program.cs
> +            Console.WriteLine("Please enter a string");
Izdzēsu no šī branch, un izmaiņas veicu "TypesAndVariables" branch

2021-07-20 12:20 UTC, endrjuki commented on csharp-basics/exercises/TypesAndVariables/Exercise8/Program.cs
> +        private const int DaysInYear = 365;
Izdzēsu no šī branch, un izmaiņas veicu "TypesAndVariables" branch

2021-07-20 12:20 UTC, endrjuki commented on csharp-basics/exercises/TypesAndVariables/Exercise6/Program.cs
> +            return numberSeries.Split(",").Aggregate(0, (accumulator, strNum) =>
Man ir izdevies atkal sajaukt kopā lietas, kurām vajadzētu atrasties 2 dažādos branchos, izdēsu `TypesUnVariables` uzdevumus no šī branch.

2021-07-20 12:20 UTC, endrjuki commented on csharp-basics/exercises/TypesAndVariables/Exercise5/Program.cs
> +            int longestIdxLength = _teachers.Length.ToString().Length;
Man ir izdevies atkal sajaukt kopā lietas, kurām vajadzētu atrasties 2 dažādos branchos.

2021-07-20 17:39 UTC, ausmoons approved these changes

2021-07-20 17:46 UTC, merged